export interface EndpointDef {
  id: string;
  label: string;
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  pathTemplate: string; // e.g. '/contracts/:contractId/partners'
  hasQueryParams?: boolean;
  hasBody?: boolean;
}

export interface ModuleDef {
  id: string;
  label: string;
  apiPrefix: string;
  icon: string;
  endpoints: EndpointDef[];
}

/** Extract path param names from a path template */
export function extractPathParams(template: string): string[] {
  const matches = template.match(/:(\w+)/g);
  return matches ? matches.map(m => m.slice(1)) : [];
}

export const MODULES: ModuleDef[] = [
  {
    id: 'impossible-cloud',
    label: 'Impossible Cloud',
    apiPrefix: '/impossible-cloud',
    icon: 'cloud',
    endpoints: [
      { id: 'list-regions', label: 'List Regions', method: 'GET', pathTemplate: '/regions' },
      { id: 'list-contracts', label: 'List Contracts', method: 'GET', pathTemplate: '/contracts' },
      { id: 'list-contract-partners', label: 'List Contract Partners', method: 'GET', pathTemplate: '/contracts/:contractId/partners' },
      { id: 'list-storage-accounts', label: 'List Storage Accounts', method: 'GET', pathTemplate: '/storage-accounts' },
      { id: 'get-storage-accounts-usage', label: 'All Storage Accounts Usage', method: 'GET', pathTemplate: '/storage-accounts/usage', hasQueryParams: true },
      { id: 'get-storage-account', label: 'Get Storage Account', method: 'GET', pathTemplate: '/storage-accounts/:accountId' },
      { id: 'get-storage-account-usage', label: 'Storage Account Usage', method: 'GET', pathTemplate: '/storage-accounts/:accountId/usage', hasQueryParams: true },
      { id: 'get-partner', label: 'Get Partner', method: 'GET', pathTemplate: '/partners/:partnerId' },
      { id: 'list-members', label: 'List Partner Members', method: 'GET', pathTemplate: '/partners/:partnerId/members' },
      { id: 'list-partner-storage-accounts', label: 'List Partner Storage Accounts', method: 'GET', pathTemplate: '/partners/:partnerId/storage-accounts' },
      { id: 'get-partner-storage-account', label: 'Get Partner Storage Account', method: 'GET', pathTemplate: '/partners/:partnerId/storage-accounts/:accountId' },
      { id: 'get-partner-storage-account-usage', label: 'Partner Storage Account Usage', method: 'GET', pathTemplate: '/partners/:partnerId/storage-accounts/:accountId/usage', hasQueryParams: true },
      { id: 'get-partner-usage', label: 'Partner Usage', method: 'GET', pathTemplate: '/partners/:partnerId/usage', hasQueryParams: true },
      { id: 'create-storage-account', label: 'Create Storage Account', method: 'POST', pathTemplate: '/storage-accounts', hasBody: true },
      { id: 'delete-storage-account', label: 'Delete Storage Account', method: 'DELETE', pathTemplate: '/storage-accounts/:accountId' },
      { id: 'patch-storage-account', label: 'Patch Storage Account', method: 'PATCH', pathTemplate: '/storage-accounts/:accountId', hasBody: true },
      { id: 'create-partner', label: 'Create Partner', method: 'POST', pathTemplate: '/partners', hasBody: true },
      { id: 'update-partner', label: 'Update Partner', method: 'PUT', pathTemplate: '/partners/:partnerId', hasBody: true },
      { id: 'delete-partner', label: 'Delete Partner', method: 'DELETE', pathTemplate: '/partners/:partnerId' },
      { id: 'create-member', label: 'Create Member', method: 'POST', pathTemplate: '/partners/:partnerId/members', hasBody: true },
      { id: 'delete-member', label: 'Delete Member', method: 'DELETE', pathTemplate: '/partners/:partnerId/members/:memberId' },
      { id: 'create-partner-storage-account', label: 'Create Partner Storage Account', method: 'POST', pathTemplate: '/partners/:partnerId/storage-accounts', hasBody: true },
      { id: 'delete-partner-storage-account', label: 'Delete Partner Storage Account', method: 'DELETE', pathTemplate: '/partners/:partnerId/storage-accounts/:accountId' },
      { id: 'patch-partner-storage-account', label: 'Patch Partner Storage Account', method: 'PATCH', pathTemplate: '/partners/:partnerId/storage-accounts/:accountId', hasBody: true },
    ]
  },
  {
    id: 'softvalue',
    label: 'Softvalue',
    apiPrefix: '/softvalue',
    icon: 'settings_ethernet',
    endpoints: [
      { id: 'proxy-get', label: 'Proxy GET', method: 'GET', pathTemplate: '/proxy', hasQueryParams: true },
      { id: 'get-token', label: 'Get Token', method: 'GET', pathTemplate: '/token' },
      { id: 'proxy-post', label: 'Proxy POST', method: 'POST', pathTemplate: '/proxy', hasQueryParams: true, hasBody: true },
      { id: 'proxy-put', label: 'Proxy PUT', method: 'PUT', pathTemplate: '/proxy', hasQueryParams: true, hasBody: true },
      { id: 'proxy-patch', label: 'Proxy PATCH', method: 'PATCH', pathTemplate: '/proxy', hasQueryParams: true, hasBody: true },
      { id: 'proxy-delete', label: 'Proxy DELETE', method: 'DELETE', pathTemplate: '/proxy', hasQueryParams: true },
      { id: 'update-token', label: 'Update Token', method: 'POST', pathTemplate: '/token', hasBody: true },
    ]
  },
  {
    id: 'zoho-analytics',
    label: 'Zoho Analytics',
    apiPrefix: '/zoho-analytics',
    icon: 'bar_chart',
    endpoints: [
      { id: 'list-workspaces', label: 'List Workspaces', method: 'GET', pathTemplate: '/workspaces' },
      { id: 'get-workspace', label: 'Get Workspace', method: 'GET', pathTemplate: '/workspaces/:id' },
      { id: 'list-views', label: 'List Views', method: 'GET', pathTemplate: '/workspaces/:workspaceId/views', hasQueryParams: true },
      { id: 'get-view', label: 'Get View', method: 'GET', pathTemplate: '/workspaces/:workspaceId/views/:viewId' },
      { id: 'list-reports', label: 'List Reports', method: 'GET', pathTemplate: '/workspaces/:workspaceId/reports' },
      { id: 'list-dashboards', label: 'List Dashboards', method: 'GET', pathTemplate: '/workspaces/:workspaceId/dashboards' },
      { id: 'export-data', label: 'Export Data', method: 'GET', pathTemplate: '/workspaces/:workspaceId/views/:viewId/export', hasQueryParams: true },
      { id: 'create-workspace', label: 'Create Workspace', method: 'POST', pathTemplate: '/workspaces', hasBody: true },
      { id: 'delete-workspace', label: 'Delete Workspace', method: 'DELETE', pathTemplate: '/workspaces/:id' },
      { id: 'create-view', label: 'Create View', method: 'POST', pathTemplate: '/workspaces/:workspaceId/views', hasBody: true },
      { id: 'delete-view', label: 'Delete View', method: 'DELETE', pathTemplate: '/workspaces/:workspaceId/views/:viewId' },
      { id: 'import-data', label: 'Import Data', method: 'POST', pathTemplate: '/import', hasBody: true },
    ]
  },
  {
    id: 'zoho-books',
    label: 'Zoho Books',
    apiPrefix: '/zoho-books',
    icon: 'menu_book',
    endpoints: [
      { id: 'list-contacts', label: 'List Contacts', method: 'GET', pathTemplate: '/contacts', hasQueryParams: true },
      { id: 'get-contact', label: 'Get Contact', method: 'GET', pathTemplate: '/contacts/:id' },
      { id: 'list-invoices', label: 'List Invoices', method: 'GET', pathTemplate: '/invoices', hasQueryParams: true },
      { id: 'get-invoice', label: 'Get Invoice', method: 'GET', pathTemplate: '/invoices/:id' },
      { id: 'list-bills', label: 'List Bills', method: 'GET', pathTemplate: '/bills', hasQueryParams: true },
      { id: 'get-bill', label: 'Get Bill', method: 'GET', pathTemplate: '/bills/:id' },
      { id: 'list-expenses', label: 'List Expenses', method: 'GET', pathTemplate: '/expenses', hasQueryParams: true },
      { id: 'get-expense', label: 'Get Expense', method: 'GET', pathTemplate: '/expenses/:id' },
      { id: 'list-payments', label: 'List Payments', method: 'GET', pathTemplate: '/payments', hasQueryParams: true },
      { id: 'get-payment', label: 'Get Payment', method: 'GET', pathTemplate: '/payments/:id' },
      { id: 'list-items', label: 'List Items', method: 'GET', pathTemplate: '/items', hasQueryParams: true },
      { id: 'get-item', label: 'Get Item', method: 'GET', pathTemplate: '/items/:id' },
      { id: 'create-contact', label: 'Create Contact', method: 'POST', pathTemplate: '/contacts', hasBody: true },
      { id: 'update-contact', label: 'Update Contact', method: 'PUT', pathTemplate: '/contacts/:id', hasBody: true },
      { id: 'delete-contact', label: 'Delete Contact', method: 'DELETE', pathTemplate: '/contacts/:id' },
      { id: 'create-invoice', label: 'Create Invoice', method: 'POST', pathTemplate: '/invoices', hasBody: true },
      { id: 'update-invoice', label: 'Update Invoice', method: 'PUT', pathTemplate: '/invoices/:id', hasBody: true },
      { id: 'delete-invoice', label: 'Delete Invoice', method: 'DELETE', pathTemplate: '/invoices/:id' },
      { id: 'send-invoice', label: 'Send Invoice', method: 'POST', pathTemplate: '/invoices/:id/send', hasBody: true },
      { id: 'mark-invoice-sent', label: 'Mark Invoice as Sent', method: 'POST', pathTemplate: '/invoices/:id/sent' },
      { id: 'void-invoice', label: 'Void Invoice', method: 'POST', pathTemplate: '/invoices/:id/void' },
      { id: 'create-bill', label: 'Create Bill', method: 'POST', pathTemplate: '/bills', hasBody: true },
      { id: 'update-bill', label: 'Update Bill', method: 'PUT', pathTemplate: '/bills/:id', hasBody: true },
      { id: 'delete-bill', label: 'Delete Bill', method: 'DELETE', pathTemplate: '/bills/:id' },
      { id: 'create-expense', label: 'Create Expense', method: 'POST', pathTemplate: '/expenses', hasBody: true },
      { id: 'update-expense', label: 'Update Expense', method: 'PUT', pathTemplate: '/expenses/:id', hasBody: true },
      { id: 'delete-expense', label: 'Delete Expense', method: 'DELETE', pathTemplate: '/expenses/:id' },
      { id: 'create-payment', label: 'Create Payment', method: 'POST', pathTemplate: '/payments', hasBody: true },
      { id: 'delete-payment', label: 'Delete Payment', method: 'DELETE', pathTemplate: '/payments/:id' },
      { id: 'create-item', label: 'Create Item', method: 'POST', pathTemplate: '/items', hasBody: true },
      { id: 'update-item', label: 'Update Item', method: 'PUT', pathTemplate: '/items/:id', hasBody: true },
      { id: 'delete-item', label: 'Delete Item', method: 'DELETE', pathTemplate: '/items/:id' },
    ]
  },
  {
    id: 'zoho-campaigns',
    label: 'Zoho Campaigns',
    apiPrefix: '/zoho-campaigns',
    icon: 'campaign',
    endpoints: [
      { id: 'list-mailing-lists', label: 'List Mailing Lists', method: 'GET', pathTemplate: '/lists', hasQueryParams: true },
      { id: 'get-mailing-list', label: 'Get Mailing List', method: 'GET', pathTemplate: '/lists/:listKey' },
      { id: 'list-subscribers', label: 'List Subscribers', method: 'GET', pathTemplate: '/lists/:listKey/subscribers', hasQueryParams: true },
      { id: 'list-topics', label: 'List Topics', method: 'GET', pathTemplate: '/topics' },
      { id: 'list-campaigns', label: 'List Campaigns', method: 'GET', pathTemplate: '/campaigns', hasQueryParams: true },
      { id: 'get-campaign', label: 'Get Campaign', method: 'GET', pathTemplate: '/campaigns/:campaignKey' },
      { id: 'create-mailing-list', label: 'Create Mailing List', method: 'POST', pathTemplate: '/lists', hasBody: true },
      { id: 'delete-mailing-list', label: 'Delete Mailing List', method: 'DELETE', pathTemplate: '/lists/:listKey' },
      { id: 'add-subscriber', label: 'Add Subscriber', method: 'POST', pathTemplate: '/lists/:listKey/subscribers', hasBody: true },
      { id: 'remove-subscriber', label: 'Remove Subscriber', method: 'DELETE', pathTemplate: '/lists/:listKey/subscribers', hasQueryParams: true },
      { id: 'send-campaign', label: 'Send Campaign', method: 'POST', pathTemplate: '/campaigns/:campaignKey/send' },
      { id: 'schedule-campaign', label: 'Schedule Campaign', method: 'POST', pathTemplate: '/campaigns/:campaignKey/schedule', hasBody: true },
    ]
  },
  {
    id: 'zoho-cliq',
    label: 'Zoho Cliq',
    apiPrefix: '/zoho-cliq',
    icon: 'chat',
    endpoints: [
      { id: 'list-channels', label: 'List Channels', method: 'GET', pathTemplate: '/channels', hasQueryParams: true },
      { id: 'get-channel', label: 'Get Channel', method: 'GET', pathTemplate: '/channels/:name' },
      { id: 'list-channel-messages', label: 'List Channel Messages', method: 'GET', pathTemplate: '/channels/:name/messages' },
      { id: 'list-user-groups', label: 'List User Groups', method: 'GET', pathTemplate: '/usergroups' },
      { id: 'get-user-group', label: 'Get User Group', method: 'GET', pathTemplate: '/usergroups/:name' },
      { id: 'list-bots', label: 'List Bots', method: 'GET', pathTemplate: '/bots' },
      { id: 'create-channel', label: 'Create Channel', method: 'POST', pathTemplate: '/channels', hasBody: true },
      { id: 'delete-channel', label: 'Delete Channel', method: 'DELETE', pathTemplate: '/channels/:name' },
      { id: 'add-channel-member', label: 'Add Channel Member', method: 'POST', pathTemplate: '/channels/:name/members', hasBody: true },
      { id: 'remove-channel-member', label: 'Remove Channel Member', method: 'DELETE', pathTemplate: '/channels/:name/members', hasQueryParams: true },
      { id: 'send-channel-message', label: 'Send Channel Message', method: 'POST', pathTemplate: '/channels/:name/message', hasBody: true },
      { id: 'delete-message', label: 'Delete Message', method: 'DELETE', pathTemplate: '/channels/:name/messages/:messageId' },
      { id: 'send-direct-message', label: 'Send Direct Message', method: 'POST', pathTemplate: '/direct/:email', hasBody: true },
      { id: 'create-user-group', label: 'Create User Group', method: 'POST', pathTemplate: '/usergroups', hasBody: true },
      { id: 'send-bot-message', label: 'Send Bot Message', method: 'POST', pathTemplate: '/bots/:name/message', hasBody: true },
    ]
  },
  {
    id: 'zoho-commerce',
    label: 'Zoho Commerce',
    apiPrefix: '/zoho-commerce',
    icon: 'storefront',
    endpoints: [
      { id: 'list-products', label: 'List Products', method: 'GET', pathTemplate: '/products', hasQueryParams: true },
      { id: 'get-product', label: 'Get Product', method: 'GET', pathTemplate: '/products/:id' },
      { id: 'list-categories', label: 'List Categories', method: 'GET', pathTemplate: '/categories' },
      { id: 'get-category', label: 'Get Category', method: 'GET', pathTemplate: '/categories/:id' },
      { id: 'list-customers', label: 'List Customers', method: 'GET', pathTemplate: '/customers', hasQueryParams: true },
      { id: 'get-customer', label: 'Get Customer', method: 'GET', pathTemplate: '/customers/:id' },
      { id: 'list-orders', label: 'List Orders', method: 'GET', pathTemplate: '/orders', hasQueryParams: true },
      { id: 'get-order', label: 'Get Order', method: 'GET', pathTemplate: '/orders/:id' },
      { id: 'create-product', label: 'Create Product', method: 'POST', pathTemplate: '/products', hasBody: true },
      { id: 'update-product', label: 'Update Product', method: 'PUT', pathTemplate: '/products/:id', hasBody: true },
      { id: 'delete-product', label: 'Delete Product', method: 'DELETE', pathTemplate: '/products/:id' },
      { id: 'create-category', label: 'Create Category', method: 'POST', pathTemplate: '/categories', hasBody: true },
      { id: 'delete-category', label: 'Delete Category', method: 'DELETE', pathTemplate: '/categories/:id' },
      { id: 'create-order', label: 'Create Order', method: 'POST', pathTemplate: '/orders', hasBody: true },
      { id: 'update-order-status', label: 'Update Order Status', method: 'PUT', pathTemplate: '/orders/:id/status', hasBody: true },
      { id: 'cancel-order', label: 'Cancel Order', method: 'POST', pathTemplate: '/orders/:id/cancel' },
    ]
  },
  {
    id: 'zoho-creator',
    label: 'Zoho Creator',
    apiPrefix: '/zoho-creator',
    icon: 'create',
    endpoints: [
      { id: 'list-applications', label: 'List Applications', method: 'GET', pathTemplate: '/applications' },
      { id: 'get-application', label: 'Get Application', method: 'GET', pathTemplate: '/applications/:appLinkName' },
      { id: 'list-forms', label: 'List Forms', method: 'GET', pathTemplate: '/applications/:appLinkName/forms' },
      { id: 'get-form', label: 'Get Form', method: 'GET', pathTemplate: '/applications/:appLinkName/forms/:formLinkName' },
      { id: 'list-reports', label: 'List Reports', method: 'GET', pathTemplate: '/applications/:appLinkName/reports' },
      { id: 'list-records', label: 'List Records', method: 'GET', pathTemplate: '/applications/:appLinkName/reports/:reportLinkName/records', hasQueryParams: true },
      { id: 'get-record', label: 'Get Record', method: 'GET', pathTemplate: '/applications/:appLinkName/reports/:reportLinkName/records/:id' },
      { id: 'create-record', label: 'Create Record', method: 'POST', pathTemplate: '/applications/:appLinkName/forms/:formLinkName/records', hasBody: true },
      { id: 'update-record', label: 'Update Record', method: 'PUT', pathTemplate: '/applications/:appLinkName/reports/:reportLinkName/records/:id', hasBody: true },
      { id: 'delete-record', label: 'Delete Record', method: 'DELETE', pathTemplate: '/applications/:appLinkName/reports/:reportLinkName/records/:id' },
      { id: 'trigger-workflow', label: 'Trigger Workflow', method: 'POST', pathTemplate: '/applications/:appLinkName/workflows/:workflowName/trigger', hasBody: true },
    ]
  },
  {
    id: 'zoho-crm',
    label: 'Zoho CRM',
    apiPrefix: '/zoho-crm',
    icon: 'people',
    endpoints: [
      { id: 'list-leads', label: 'List Leads', method: 'GET', pathTemplate: '/leads', hasQueryParams: true },
      { id: 'get-lead', label: 'Get Lead', method: 'GET', pathTemplate: '/leads/:id' },
      { id: 'search-leads', label: 'Search Leads', method: 'GET', pathTemplate: '/leads/search', hasQueryParams: true },
      { id: 'list-contacts', label: 'List Contacts', method: 'GET', pathTemplate: '/contacts', hasQueryParams: true },
      { id: 'get-contact', label: 'Get Contact', method: 'GET', pathTemplate: '/contacts/:id' },
      { id: 'list-accounts', label: 'List Accounts', method: 'GET', pathTemplate: '/accounts', hasQueryParams: true },
      { id: 'get-account', label: 'Get Account', method: 'GET', pathTemplate: '/accounts/:id' },
      { id: 'list-deals', label: 'List Deals', method: 'GET', pathTemplate: '/deals', hasQueryParams: true },
      { id: 'get-deal', label: 'Get Deal', method: 'GET', pathTemplate: '/deals/:id' },
      { id: 'list-tasks', label: 'List Tasks', method: 'GET', pathTemplate: '/tasks', hasQueryParams: true },
      { id: 'get-task', label: 'Get Task', method: 'GET', pathTemplate: '/tasks/:id' },
      { id: 'list-notes', label: 'List Notes', method: 'GET', pathTemplate: '/notes', hasQueryParams: true },
      { id: 'get-note', label: 'Get Note', method: 'GET', pathTemplate: '/notes/:id' },
      { id: 'list-module-records', label: 'List Module Records', method: 'GET', pathTemplate: '/modules/:module', hasQueryParams: true },
      { id: 'get-module-record', label: 'Get Module Record', method: 'GET', pathTemplate: '/modules/:module/:id' },
      { id: 'create-leads', label: 'Create Leads', method: 'POST', pathTemplate: '/leads', hasBody: true },
      { id: 'update-leads', label: 'Update Leads', method: 'PUT', pathTemplate: '/leads', hasBody: true },
      { id: 'delete-lead', label: 'Delete Lead', method: 'DELETE', pathTemplate: '/leads/:id' },
      { id: 'create-contacts', label: 'Create Contacts', method: 'POST', pathTemplate: '/contacts', hasBody: true },
      { id: 'update-contacts', label: 'Update Contacts', method: 'PUT', pathTemplate: '/contacts', hasBody: true },
      { id: 'delete-contact', label: 'Delete Contact', method: 'DELETE', pathTemplate: '/contacts/:id' },
      { id: 'create-accounts', label: 'Create Accounts', method: 'POST', pathTemplate: '/accounts', hasBody: true },
      { id: 'update-accounts', label: 'Update Accounts', method: 'PUT', pathTemplate: '/accounts', hasBody: true },
      { id: 'delete-account', label: 'Delete Account', method: 'DELETE', pathTemplate: '/accounts/:id' },
      { id: 'create-deals', label: 'Create Deals', method: 'POST', pathTemplate: '/deals', hasBody: true },
      { id: 'update-deals', label: 'Update Deals', method: 'PUT', pathTemplate: '/deals', hasBody: true },
      { id: 'delete-deal', label: 'Delete Deal', method: 'DELETE', pathTemplate: '/deals/:id' },
      { id: 'create-tasks', label: 'Create Tasks', method: 'POST', pathTemplate: '/tasks', hasBody: true },
      { id: 'update-tasks', label: 'Update Tasks', method: 'PUT', pathTemplate: '/tasks', hasBody: true },
      { id: 'delete-task', label: 'Delete Task', method: 'DELETE', pathTemplate: '/tasks/:id' },
      { id: 'create-notes', label: 'Create Notes', method: 'POST', pathTemplate: '/notes', hasBody: true },
      { id: 'delete-note', label: 'Delete Note', method: 'DELETE', pathTemplate: '/notes/:id' },
      { id: 'create-module-records', label: 'Create Module Records', method: 'POST', pathTemplate: '/modules/:module', hasBody: true },
      { id: 'update-module-records', label: 'Update Module Records', method: 'PUT', pathTemplate: '/modules/:module', hasBody: true },
      { id: 'delete-module-record', label: 'Delete Module Record', method: 'DELETE', pathTemplate: '/modules/:module/:id' },
    ]
  },
  {
    id: 'zoho-desk',
    label: 'Zoho Desk',
    apiPrefix: '/zoho-desk',
    icon: 'support_agent',
    endpoints: [
      { id: 'list-tickets', label: 'List Tickets', method: 'GET', pathTemplate: '/tickets', hasQueryParams: true },
      { id: 'get-ticket', label: 'Get Ticket', method: 'GET', pathTemplate: '/tickets/:id' },
      { id: 'search-tickets', label: 'Search Tickets', method: 'GET', pathTemplate: '/tickets/search', hasQueryParams: true },
      { id: 'list-comments', label: 'List Comments', method: 'GET', pathTemplate: '/tickets/:ticketId/comments' },
      { id: 'list-contacts', label: 'List Contacts', method: 'GET', pathTemplate: '/contacts', hasQueryParams: true },
      { id: 'get-contact', label: 'Get Contact', method: 'GET', pathTemplate: '/contacts/:id' },
      { id: 'list-agents', label: 'List Agents', method: 'GET', pathTemplate: '/agents', hasQueryParams: true },
      { id: 'get-agent', label: 'Get Agent', method: 'GET', pathTemplate: '/agents/:id' },
      { id: 'list-departments', label: 'List Departments', method: 'GET', pathTemplate: '/departments' },
      { id: 'get-department', label: 'Get Department', method: 'GET', pathTemplate: '/departments/:id' },
      { id: 'create-ticket', label: 'Create Ticket', method: 'POST', pathTemplate: '/tickets', hasBody: true },
      { id: 'update-ticket', label: 'Update Ticket', method: 'PATCH', pathTemplate: '/tickets/:id', hasBody: true },
      { id: 'delete-ticket', label: 'Delete Ticket', method: 'DELETE', pathTemplate: '/tickets/:id' },
      { id: 'add-comment', label: 'Add Comment', method: 'POST', pathTemplate: '/tickets/:ticketId/comments', hasBody: true },
      { id: 'delete-comment', label: 'Delete Comment', method: 'DELETE', pathTemplate: '/tickets/:ticketId/comments/:commentId' },
      { id: 'create-contact', label: 'Create Contact', method: 'POST', pathTemplate: '/contacts', hasBody: true },
      { id: 'update-contact', label: 'Update Contact', method: 'PATCH', pathTemplate: '/contacts/:id', hasBody: true },
      { id: 'delete-contact', label: 'Delete Contact', method: 'DELETE', pathTemplate: '/contacts/:id' },
    ]
  },
  {
    id: 'zoho-expense',
    label: 'Zoho Expense',
    apiPrefix: '/zoho-expense',
    icon: 'receipt_long',
    endpoints: [
      { id: 'list-categories', label: 'List Categories', method: 'GET', pathTemplate: '/categories' },
      { id: 'get-category', label: 'Get Category', method: 'GET', pathTemplate: '/categories/:id' },
      { id: 'list-expenses', label: 'List Expenses', method: 'GET', pathTemplate: '/expenses', hasQueryParams: true },
      { id: 'get-expense', label: 'Get Expense', method: 'GET', pathTemplate: '/expenses/:id' },
      { id: 'list-reports', label: 'List Reports', method: 'GET', pathTemplate: '/reports', hasQueryParams: true },
      { id: 'get-report', label: 'Get Report', method: 'GET', pathTemplate: '/reports/:id' },
      { id: 'list-advances', label: 'List Advances', method: 'GET', pathTemplate: '/advances' },
      { id: 'get-advance', label: 'Get Advance', method: 'GET', pathTemplate: '/advances/:id' },
      { id: 'create-expense', label: 'Create Expense', method: 'POST', pathTemplate: '/expenses', hasBody: true },
      { id: 'update-expense', label: 'Update Expense', method: 'PUT', pathTemplate: '/expenses/:id', hasBody: true },
      { id: 'delete-expense', label: 'Delete Expense', method: 'DELETE', pathTemplate: '/expenses/:id' },
      { id: 'create-report', label: 'Create Report', method: 'POST', pathTemplate: '/reports', hasBody: true },
      { id: 'update-report', label: 'Update Report', method: 'PUT', pathTemplate: '/reports/:id', hasBody: true },
      { id: 'delete-report', label: 'Delete Report', method: 'DELETE', pathTemplate: '/reports/:id' },
      { id: 'submit-report', label: 'Submit Report', method: 'POST', pathTemplate: '/reports/:id/submit' },
      { id: 'approve-report', label: 'Approve Report', method: 'POST', pathTemplate: '/reports/:id/approve' },
    ]
  },
  {
    id: 'zoho-inventory',
    label: 'Zoho Inventory',
    apiPrefix: '/zoho-inventory',
    icon: 'inventory_2',
    endpoints: [
      { id: 'list-items', label: 'List Items', method: 'GET', pathTemplate: '/items', hasQueryParams: true },
      { id: 'get-item', label: 'Get Item', method: 'GET', pathTemplate: '/items/:id' },
      { id: 'list-warehouses', label: 'List Warehouses', method: 'GET', pathTemplate: '/warehouses' },
      { id: 'get-warehouse', label: 'Get Warehouse', method: 'GET', pathTemplate: '/warehouses/:id' },
      { id: 'list-sales-orders', label: 'List Sales Orders', method: 'GET', pathTemplate: '/salesorders', hasQueryParams: true },
      { id: 'get-sales-order', label: 'Get Sales Order', method: 'GET', pathTemplate: '/salesorders/:id' },
      { id: 'list-purchase-orders', label: 'List Purchase Orders', method: 'GET', pathTemplate: '/purchaseorders', hasQueryParams: true },
      { id: 'get-purchase-order', label: 'Get Purchase Order', method: 'GET', pathTemplate: '/purchaseorders/:id' },
      { id: 'create-item', label: 'Create Item', method: 'POST', pathTemplate: '/items', hasBody: true },
      { id: 'update-item', label: 'Update Item', method: 'PUT', pathTemplate: '/items/:id', hasBody: true },
      { id: 'delete-item', label: 'Delete Item', method: 'DELETE', pathTemplate: '/items/:id' },
      { id: 'create-sales-order', label: 'Create Sales Order', method: 'POST', pathTemplate: '/salesorders', hasBody: true },
      { id: 'update-sales-order', label: 'Update Sales Order', method: 'PUT', pathTemplate: '/salesorders/:id', hasBody: true },
      { id: 'delete-sales-order', label: 'Delete Sales Order', method: 'DELETE', pathTemplate: '/salesorders/:id' },
      { id: 'create-purchase-order', label: 'Create Purchase Order', method: 'POST', pathTemplate: '/purchaseorders', hasBody: true },
      { id: 'update-purchase-order', label: 'Update Purchase Order', method: 'PUT', pathTemplate: '/purchaseorders/:id', hasBody: true },
      { id: 'delete-purchase-order', label: 'Delete Purchase Order', method: 'DELETE', pathTemplate: '/purchaseorders/:id' },
    ]
  },
  {
    id: 'zoho-invoice',
    label: 'Zoho Invoice',
    apiPrefix: '/zoho-invoice',
    icon: 'description',
    endpoints: [
      { id: 'list-customers', label: 'List Customers', method: 'GET', pathTemplate: '/customers', hasQueryParams: true },
      { id: 'get-customer', label: 'Get Customer', method: 'GET', pathTemplate: '/customers/:id' },
      { id: 'list-invoices', label: 'List Invoices', method: 'GET', pathTemplate: '/invoices', hasQueryParams: true },
      { id: 'get-invoice', label: 'Get Invoice', method: 'GET', pathTemplate: '/invoices/:id' },
      { id: 'list-estimates', label: 'List Estimates', method: 'GET', pathTemplate: '/estimates', hasQueryParams: true },
      { id: 'get-estimate', label: 'Get Estimate', method: 'GET', pathTemplate: '/estimates/:id' },
      { id: 'list-recurring-invoices', label: 'List Recurring Invoices', method: 'GET', pathTemplate: '/recurring-invoices', hasQueryParams: true },
      { id: 'get-recurring-invoice', label: 'Get Recurring Invoice', method: 'GET', pathTemplate: '/recurring-invoices/:id' },
      { id: 'list-payments', label: 'List Payments', method: 'GET', pathTemplate: '/payments', hasQueryParams: true },
      { id: 'create-customer', label: 'Create Customer', method: 'POST', pathTemplate: '/customers', hasBody: true },
      { id: 'update-customer', label: 'Update Customer', method: 'PUT', pathTemplate: '/customers/:id', hasBody: true },
      { id: 'delete-customer', label: 'Delete Customer', method: 'DELETE', pathTemplate: '/customers/:id' },
      { id: 'create-invoice', label: 'Create Invoice', method: 'POST', pathTemplate: '/invoices', hasBody: true },
      { id: 'update-invoice', label: 'Update Invoice', method: 'PUT', pathTemplate: '/invoices/:id', hasBody: true },
      { id: 'delete-invoice', label: 'Delete Invoice', method: 'DELETE', pathTemplate: '/invoices/:id' },
      { id: 'send-invoice', label: 'Send Invoice', method: 'POST', pathTemplate: '/invoices/:id/send' },
      { id: 'create-estimate', label: 'Create Estimate', method: 'POST', pathTemplate: '/estimates', hasBody: true },
      { id: 'update-estimate', label: 'Update Estimate', method: 'PUT', pathTemplate: '/estimates/:id', hasBody: true },
      { id: 'delete-estimate', label: 'Delete Estimate', method: 'DELETE', pathTemplate: '/estimates/:id' },
      { id: 'create-recurring-invoice', label: 'Create Recurring Invoice', method: 'POST', pathTemplate: '/recurring-invoices', hasBody: true },
      { id: 'delete-recurring-invoice', label: 'Delete Recurring Invoice', method: 'DELETE', pathTemplate: '/recurring-invoices/:id' },
      { id: 'create-payment', label: 'Create Payment', method: 'POST', pathTemplate: '/payments', hasBody: true },
      { id: 'delete-payment', label: 'Delete Payment', method: 'DELETE', pathTemplate: '/payments/:id' },
    ]
  },
  {
    id: 'zoho-mail',
    label: 'Zoho Mail',
    apiPrefix: '/zoho-mail',
    icon: 'mail',
    endpoints: [
      { id: 'list-accounts', label: 'List Accounts', method: 'GET', pathTemplate: '/accounts' },
      { id: 'get-account', label: 'Get Account', method: 'GET', pathTemplate: '/accounts/:accountId' },
      { id: 'list-folders', label: 'List Folders', method: 'GET', pathTemplate: '/accounts/:accountId/folders' },
      { id: 'list-messages', label: 'List Messages', method: 'GET', pathTemplate: '/accounts/:accountId/folders/:folderId/messages', hasQueryParams: true },
      { id: 'search-messages', label: 'Search Messages', method: 'GET', pathTemplate: '/accounts/:accountId/messages/search', hasQueryParams: true },
      { id: 'get-message', label: 'Get Message', method: 'GET', pathTemplate: '/accounts/:accountId/messages/:messageId' },
      { id: 'list-contacts', label: 'List Contacts', method: 'GET', pathTemplate: '/accounts/:accountId/contacts' },
      { id: 'send-message', label: 'Send Message', method: 'POST', pathTemplate: '/accounts/:accountId/messages', hasBody: true },
      { id: 'delete-message', label: 'Delete Message', method: 'DELETE', pathTemplate: '/accounts/:accountId/messages/:messageId' },
      { id: 'move-message', label: 'Move Message', method: 'POST', pathTemplate: '/accounts/:accountId/messages/:messageId/move', hasBody: true },
      { id: 'mark-read', label: 'Mark Read', method: 'POST', pathTemplate: '/accounts/:accountId/messages/:messageId/read', hasBody: true },
      { id: 'create-contact', label: 'Create Contact', method: 'POST', pathTemplate: '/accounts/:accountId/contacts', hasBody: true },
      { id: 'delete-contact', label: 'Delete Contact', method: 'DELETE', pathTemplate: '/accounts/:accountId/contacts/:contactId' },
    ]
  },
  {
    id: 'zoho-payroll',
    label: 'Zoho Payroll',
    apiPrefix: '/zoho-payroll',
    icon: 'payments',
    endpoints: [
      { id: 'list-employees', label: 'List Employees', method: 'GET', pathTemplate: '/employees', hasQueryParams: true },
      { id: 'get-employee', label: 'Get Employee', method: 'GET', pathTemplate: '/employees/:id' },
      { id: 'list-pay-components', label: 'List Pay Components', method: 'GET', pathTemplate: '/pay-components' },
      { id: 'get-pay-component', label: 'Get Pay Component', method: 'GET', pathTemplate: '/pay-components/:id' },
      { id: 'list-pay-runs', label: 'List Pay Runs', method: 'GET', pathTemplate: '/payruns', hasQueryParams: true },
      { id: 'get-pay-run', label: 'Get Pay Run', method: 'GET', pathTemplate: '/payruns/:id' },
      { id: 'list-payslips', label: 'List Payslips', method: 'GET', pathTemplate: '/payruns/:payRunId/payslips' },
      { id: 'get-payslip', label: 'Get Payslip', method: 'GET', pathTemplate: '/payruns/:payRunId/payslips/:payslipId' },
      { id: 'list-declarations', label: 'List Declarations', method: 'GET', pathTemplate: '/declarations', hasQueryParams: true },
      { id: 'get-declaration', label: 'Get Declaration', method: 'GET', pathTemplate: '/declarations/:id' },
      { id: 'create-employee', label: 'Create Employee', method: 'POST', pathTemplate: '/employees', hasBody: true },
      { id: 'update-employee', label: 'Update Employee', method: 'PUT', pathTemplate: '/employees/:id', hasBody: true },
      { id: 'terminate-employee', label: 'Terminate Employee', method: 'POST', pathTemplate: '/employees/:id/terminate', hasBody: true },
      { id: 'create-pay-run', label: 'Create Pay Run', method: 'POST', pathTemplate: '/payruns', hasBody: true },
      { id: 'approve-pay-run', label: 'Approve Pay Run', method: 'POST', pathTemplate: '/payruns/:id/approve' },
    ]
  },
  {
    id: 'zoho-people',
    label: 'Zoho People',
    apiPrefix: '/zoho-people',
    icon: 'badge',
    endpoints: [
      { id: 'list-employees', label: 'List Employees', method: 'GET', pathTemplate: '/employees', hasQueryParams: true },
      { id: 'get-employee', label: 'Get Employee', method: 'GET', pathTemplate: '/employees/:id' },
      { id: 'list-departments', label: 'List Departments', method: 'GET', pathTemplate: '/departments' },
      { id: 'list-leave-types', label: 'List Leave Types', method: 'GET', pathTemplate: '/leave-types' },
      { id: 'list-leave-requests', label: 'List Leave Requests', method: 'GET', pathTemplate: '/leave-requests', hasQueryParams: true },
      { id: 'list-attendance', label: 'List Attendance', method: 'GET', pathTemplate: '/attendance/:empId', hasQueryParams: true },
      { id: 'get-form-records', label: 'Get Form Records', method: 'GET', pathTemplate: '/forms/:formName/records', hasQueryParams: true },
      { id: 'add-employee', label: 'Add Employee', method: 'POST', pathTemplate: '/employees', hasBody: true },
      { id: 'update-employee', label: 'Update Employee', method: 'POST', pathTemplate: '/employees/:id', hasBody: true },
      { id: 'delete-employee', label: 'Delete Employee', method: 'DELETE', pathTemplate: '/employees/:id' },
      { id: 'add-leave-request', label: 'Add Leave Request', method: 'POST', pathTemplate: '/leave-requests', hasBody: true },
      { id: 'approve-leave', label: 'Approve Leave', method: 'POST', pathTemplate: '/leave-requests/:id/approve' },
      { id: 'reject-leave', label: 'Reject Leave', method: 'POST', pathTemplate: '/leave-requests/:id/reject', hasBody: true },
      { id: 'add-form-record', label: 'Add Form Record', method: 'POST', pathTemplate: '/forms/:formName/records', hasBody: true },
      { id: 'update-form-record', label: 'Update Form Record', method: 'POST', pathTemplate: '/forms/:formName/records/:id', hasBody: true },
    ]
  },
  {
    id: 'zoho-projects',
    label: 'Zoho Projects',
    apiPrefix: '/zoho-projects',
    icon: 'folder_open',
    endpoints: [
      { id: 'list-projects', label: 'List Projects', method: 'GET', pathTemplate: '/projects', hasQueryParams: true },
      { id: 'get-project', label: 'Get Project', method: 'GET', pathTemplate: '/projects/:id' },
      { id: 'list-tasks', label: 'List Tasks', method: 'GET', pathTemplate: '/projects/:projectId/tasks', hasQueryParams: true },
      { id: 'get-task', label: 'Get Task', method: 'GET', pathTemplate: '/projects/:projectId/tasks/:taskId' },
      { id: 'list-milestones', label: 'List Milestones', method: 'GET', pathTemplate: '/projects/:projectId/milestones' },
      { id: 'list-bugs', label: 'List Bugs', method: 'GET', pathTemplate: '/projects/:projectId/bugs' },
      { id: 'get-bug', label: 'Get Bug', method: 'GET', pathTemplate: '/projects/:projectId/bugs/:bugId' },
      { id: 'list-timelogs', label: 'List Time Logs', method: 'GET', pathTemplate: '/projects/:projectId/timelogs' },
      { id: 'create-project', label: 'Create Project', method: 'POST', pathTemplate: '/projects', hasBody: true },
      { id: 'update-project', label: 'Update Project', method: 'POST', pathTemplate: '/projects/:id', hasBody: true },
      { id: 'delete-project', label: 'Delete Project', method: 'DELETE', pathTemplate: '/projects/:id' },
      { id: 'create-task', label: 'Create Task', method: 'POST', pathTemplate: '/projects/:projectId/tasks', hasBody: true },
      { id: 'update-task', label: 'Update Task', method: 'POST', pathTemplate: '/projects/:projectId/tasks/:taskId', hasBody: true },
      { id: 'delete-task', label: 'Delete Task', method: 'DELETE', pathTemplate: '/projects/:projectId/tasks/:taskId' },
      { id: 'create-bug', label: 'Create Bug', method: 'POST', pathTemplate: '/projects/:projectId/bugs', hasBody: true },
      { id: 'update-bug', label: 'Update Bug', method: 'POST', pathTemplate: '/projects/:projectId/bugs/:bugId', hasBody: true },
      { id: 'delete-bug', label: 'Delete Bug', method: 'DELETE', pathTemplate: '/projects/:projectId/bugs/:bugId' },
      { id: 'add-timelog', label: 'Add Time Log', method: 'POST', pathTemplate: '/projects/:projectId/tasks/:taskId/timelogs', hasBody: true },
      { id: 'delete-timelog', label: 'Delete Time Log', method: 'DELETE', pathTemplate: '/projects/:projectId/tasks/:taskId/timelogs/:logId' },
    ]
  },
  {
    id: 'zoho-recruit',
    label: 'Zoho Recruit',
    apiPrefix: '/zoho-recruit',
    icon: 'work',
    endpoints: [
      { id: 'list-job-openings', label: 'List Job Openings', method: 'GET', pathTemplate: '/job-openings', hasQueryParams: true },
      { id: 'get-job-opening', label: 'Get Job Opening', method: 'GET', pathTemplate: '/job-openings/:id' },
      { id: 'list-candidates', label: 'List Candidates', method: 'GET', pathTemplate: '/candidates', hasQueryParams: true },
      { id: 'get-candidate', label: 'Get Candidate', method: 'GET', pathTemplate: '/candidates/:id' },
      { id: 'search-candidates', label: 'Search Candidates', method: 'GET', pathTemplate: '/candidates/search', hasQueryParams: true },
      { id: 'list-interviews', label: 'List Interviews', method: 'GET', pathTemplate: '/interviews', hasQueryParams: true },
      { id: 'get-interview', label: 'Get Interview', method: 'GET', pathTemplate: '/interviews/:id' },
      { id: 'list-offers', label: 'List Offers', method: 'GET', pathTemplate: '/offers', hasQueryParams: true },
      { id: 'get-offer', label: 'Get Offer', method: 'GET', pathTemplate: '/offers/:id' },
      { id: 'create-job-openings', label: 'Create Job Openings', method: 'POST', pathTemplate: '/job-openings', hasBody: true },
      { id: 'update-job-openings', label: 'Update Job Openings', method: 'PUT', pathTemplate: '/job-openings', hasBody: true },
      { id: 'delete-job-opening', label: 'Delete Job Opening', method: 'DELETE', pathTemplate: '/job-openings/:id' },
      { id: 'create-candidates', label: 'Create Candidates', method: 'POST', pathTemplate: '/candidates', hasBody: true },
      { id: 'update-candidates', label: 'Update Candidates', method: 'PUT', pathTemplate: '/candidates', hasBody: true },
      { id: 'delete-candidate', label: 'Delete Candidate', method: 'DELETE', pathTemplate: '/candidates/:id' },
      { id: 'create-interviews', label: 'Create Interviews', method: 'POST', pathTemplate: '/interviews', hasBody: true },
      { id: 'delete-interview', label: 'Delete Interview', method: 'DELETE', pathTemplate: '/interviews/:id' },
    ]
  },
  {
    id: 'zoho-salesiq',
    label: 'Zoho SalesIQ',
    apiPrefix: '/zoho-salesiq',
    icon: 'forum',
    endpoints: [
      { id: 'list-visitors', label: 'List Visitors', method: 'GET', pathTemplate: '/:screenName/visitors', hasQueryParams: true },
      { id: 'get-visitor', label: 'Get Visitor', method: 'GET', pathTemplate: '/:screenName/visitors/:visitorId' },
      { id: 'search-visitors', label: 'Search Visitors', method: 'GET', pathTemplate: '/:screenName/visitors/search', hasQueryParams: true },
      { id: 'list-chats', label: 'List Chats', method: 'GET', pathTemplate: '/:screenName/chats', hasQueryParams: true },
      { id: 'get-chat', label: 'Get Chat', method: 'GET', pathTemplate: '/:screenName/chats/:chatId' },
      { id: 'list-chat-messages', label: 'List Chat Messages', method: 'GET', pathTemplate: '/:screenName/chats/:chatId/messages' },
      { id: 'list-operators', label: 'List Operators', method: 'GET', pathTemplate: '/:screenName/operators' },
      { id: 'get-operator', label: 'Get Operator', method: 'GET', pathTemplate: '/:screenName/operators/:operatorId' },
      { id: 'list-departments', label: 'List Departments', method: 'GET', pathTemplate: '/:screenName/departments' },
      { id: 'list-bots', label: 'List Bots', method: 'GET', pathTemplate: '/:screenName/bots' },
      { id: 'list-feedback-forms', label: 'List Feedback Forms', method: 'GET', pathTemplate: '/:screenName/feedback-forms' },
      { id: 'send-chat-message', label: 'Send Chat Message', method: 'POST', pathTemplate: '/:screenName/chats/:chatId/messages', hasBody: true },
      { id: 'set-rating', label: 'Set Chat Rating', method: 'POST', pathTemplate: '/:screenName/chats/:chatId/rating', hasBody: true },
      { id: 'set-operator-availability', label: 'Set Operator Availability', method: 'POST', pathTemplate: '/:screenName/operators/:operatorId/availability', hasBody: true },
      { id: 'send-bot-message', label: 'Send Bot Message', method: 'POST', pathTemplate: '/:screenName/bots/:botId/messages', hasBody: true },
    ]
  },
  {
    id: 'zoho-sign',
    label: 'Zoho Sign',
    apiPrefix: '/zoho-sign',
    icon: 'draw',
    endpoints: [
      { id: 'list-requests', label: 'List Requests', method: 'GET', pathTemplate: '/requests', hasQueryParams: true },
      { id: 'get-request', label: 'Get Request', method: 'GET', pathTemplate: '/requests/:id' },
      { id: 'list-templates', label: 'List Templates', method: 'GET', pathTemplate: '/templates', hasQueryParams: true },
      { id: 'get-template', label: 'Get Template', method: 'GET', pathTemplate: '/templates/:id' },
      { id: 'get-document', label: 'Get Document', method: 'GET', pathTemplate: '/requests/:requestId/documents/:documentId' },
      { id: 'download-document', label: 'Download Document', method: 'GET', pathTemplate: '/requests/:requestId/documents/:documentId/download' },
      { id: 'create-request', label: 'Create Request', method: 'POST', pathTemplate: '/requests', hasBody: true },
      { id: 'send-request', label: 'Send Request', method: 'POST', pathTemplate: '/requests/:id/send' },
      { id: 'delete-request', label: 'Delete Request', method: 'DELETE', pathTemplate: '/requests/:id' },
      { id: 'recall-request', label: 'Recall Request', method: 'POST', pathTemplate: '/requests/:id/recall' },
      { id: 'remind-request', label: 'Remind Request', method: 'POST', pathTemplate: '/requests/:id/remind' },
      { id: 'create-request-from-template', label: 'Create Request from Template', method: 'POST', pathTemplate: '/templates/:id/create-request', hasBody: true },
    ]
  },
  {
    id: 'zoho-subscriptions',
    label: 'Zoho Subscriptions',
    apiPrefix: '/zoho-subscriptions',
    icon: 'subscriptions',
    endpoints: [
      { id: 'list-plans', label: 'List Plans', method: 'GET', pathTemplate: '/plans', hasQueryParams: true },
      { id: 'get-plan', label: 'Get Plan', method: 'GET', pathTemplate: '/plans/:code' },
      { id: 'list-addons', label: 'List Addons', method: 'GET', pathTemplate: '/addons' },
      { id: 'get-addon', label: 'Get Addon', method: 'GET', pathTemplate: '/addons/:code' },
      { id: 'list-coupons', label: 'List Coupons', method: 'GET', pathTemplate: '/coupons' },
      { id: 'get-coupon', label: 'Get Coupon', method: 'GET', pathTemplate: '/coupons/:code' },
      { id: 'list-customers', label: 'List Customers', method: 'GET', pathTemplate: '/customers', hasQueryParams: true },
      { id: 'get-customer', label: 'Get Customer', method: 'GET', pathTemplate: '/customers/:id' },
      { id: 'list-subscriptions', label: 'List Subscriptions', method: 'GET', pathTemplate: '/subscriptions', hasQueryParams: true },
      { id: 'get-subscription', label: 'Get Subscription', method: 'GET', pathTemplate: '/subscriptions/:id' },
      { id: 'create-plan', label: 'Create Plan', method: 'POST', pathTemplate: '/plans', hasBody: true },
      { id: 'update-plan', label: 'Update Plan', method: 'PUT', pathTemplate: '/plans/:code', hasBody: true },
      { id: 'delete-plan', label: 'Delete Plan', method: 'DELETE', pathTemplate: '/plans/:code' },
      { id: 'create-customer', label: 'Create Customer', method: 'POST', pathTemplate: '/customers', hasBody: true },
      { id: 'update-customer', label: 'Update Customer', method: 'PUT', pathTemplate: '/customers/:id', hasBody: true },
      { id: 'delete-customer', label: 'Delete Customer', method: 'DELETE', pathTemplate: '/customers/:id' },
      { id: 'create-subscription', label: 'Create Subscription', method: 'POST', pathTemplate: '/subscriptions', hasBody: true },
      { id: 'update-subscription', label: 'Update Subscription', method: 'PUT', pathTemplate: '/subscriptions/:id', hasBody: true },
      { id: 'cancel-subscription', label: 'Cancel Subscription', method: 'POST', pathTemplate: '/subscriptions/:id/cancel' },
      { id: 'reactivate-subscription', label: 'Reactivate Subscription', method: 'POST', pathTemplate: '/subscriptions/:id/reactivate' },
    ]
  },
  {
    id: 'zoho-workdrive',
    label: 'Zoho WorkDrive',
    apiPrefix: '/zoho-workdrive',
    icon: 'drive_folder_upload',
    endpoints: [
      { id: 'list-teams', label: 'List Teams', method: 'GET', pathTemplate: '/teams' },
      { id: 'get-team', label: 'Get Team', method: 'GET', pathTemplate: '/teams/:id' },
      { id: 'search-files', label: 'Search Files', method: 'GET', pathTemplate: '/teams/:teamId/files/search', hasQueryParams: true },
      { id: 'get-folder', label: 'Get Folder', method: 'GET', pathTemplate: '/folders/:id' },
      { id: 'list-folder-contents', label: 'List Folder Contents', method: 'GET', pathTemplate: '/folders/:folderId/files', hasQueryParams: true },
      { id: 'get-file', label: 'Get File', method: 'GET', pathTemplate: '/files/:id' },
      { id: 'get-sharelink', label: 'Get Share Link', method: 'GET', pathTemplate: '/files/:fileId/sharelinks' },
      { id: 'list-workspace-members', label: 'List Workspace Members', method: 'GET', pathTemplate: '/workspaces/:workspaceId/members' },
      { id: 'create-folder', label: 'Create Folder', method: 'POST', pathTemplate: '/folders', hasBody: true },
      { id: 'rename-folder', label: 'Rename Folder', method: 'PATCH', pathTemplate: '/folders/:id/rename', hasBody: true },
      { id: 'delete-folder', label: 'Delete Folder', method: 'DELETE', pathTemplate: '/folders/:id' },
      { id: 'copy-file', label: 'Copy File', method: 'POST', pathTemplate: '/files/:fileId/copy', hasBody: true },
      { id: 'move-file', label: 'Move File', method: 'PATCH', pathTemplate: '/files/:fileId/move', hasBody: true },
      { id: 'delete-file', label: 'Delete File', method: 'DELETE', pathTemplate: '/files/:id' },
      { id: 'create-sharelink', label: 'Create Share Link', method: 'POST', pathTemplate: '/sharelinks', hasBody: true },
      { id: 'add-workspace-member', label: 'Add Workspace Member', method: 'POST', pathTemplate: '/workspaces/:workspaceId/members', hasBody: true },
      { id: 'remove-workspace-member', label: 'Remove Workspace Member', method: 'DELETE', pathTemplate: '/workspaces/:workspaceId/members/:memberId' },
    ]
  },
  {
    id: 'chatgpt',
    label: 'ChatGPT',
    apiPrefix: '/chatgpt',
    icon: 'psychology',
    endpoints: [
      { id: 'list-models', label: 'List Models', method: 'GET', pathTemplate: '/models' },
      { id: 'get-model', label: 'Get Model', method: 'GET', pathTemplate: '/models/:modelId' },
      { id: 'create-chat-completion', label: 'Chat Completion', method: 'POST', pathTemplate: '/chat/completions', hasBody: true },
      { id: 'create-embedding', label: 'Create Embedding', method: 'POST', pathTemplate: '/embeddings', hasBody: true },
      { id: 'generate-image', label: 'Generate Image', method: 'POST', pathTemplate: '/images/generations', hasBody: true },
      { id: 'create-moderation', label: 'Create Moderation', method: 'POST', pathTemplate: '/moderations', hasBody: true },
    ]
  },
];

export const MODULE_MAP = new Map<string, ModuleDef>(MODULES.map(m => [m.id, m]));
