import { IAuthProvider } from "./IAuthProvider";

const EXPIRY_BUFFER_MS = 60_000;

// ─── Types ────────────────────────────────────────────────────────────────────

export interface CustomTokenResult {
  /** The access token string to place in the Authorization header. */
  accessToken: string;
  /**
   * Unix timestamp in milliseconds when the token expires.
   * If omitted the token is treated as single-use (fetched on every request).
   */
  expiresAt?: number;
}

/**
 * A function that fetches or generates a valid Zoho access token.
 * Can be async (e.g. call your own secrets manager, identity provider,
 * sign a JWT, forward from a parent process, etc.).
 */
export type CustomTokenFetcher = () => Promise<CustomTokenResult>;

export interface CustomAuthConfig {
  /**
   * Async function called whenever a new token is needed.
   * Receives the reason: "initial" | "expired" | "invalidated"
   */
  fetchToken: (reason: "initial" | "expired" | "invalidated") => Promise<CustomTokenResult>;
  /**
   * Optional – called when a 401 is received BEFORE the token is invalidated
   * and retried. Use this to log or alert your upstream system.
   */
  onInvalidate?: () => void;
}

// ─── CustomAuthProvider ───────────────────────────────────────────────────────

/**
 * Auth strategy: Custom / bring-your-own token fetcher
 *
 * Delegate the entire token-acquisition logic to a user-supplied async
 * function. This is the escape hatch for any scenario not covered by the
 * built-in providers:
 *
 *  - Tokens generated by an internal SSO / identity provider
 *  - Tokens forwarded from a parent service or API gateway
 *  - Custom JWT signing before exchanging with Zoho
 *  - Wrapping an SDK that already manages OAuth internally
 *  - Testing / mocking with deterministic tokens
 *
 * @example
 * ```ts
 * const auth = new CustomAuthProvider({
 *   fetchToken: async (reason) => {
 *     const { token, expiresIn } = await mySecretsManager.getZohoToken();
 *     return { accessToken: token, expiresAt: Date.now() + expiresIn * 1000 };
 *   },
 *   onInvalidate: () => console.warn("Zoho returned 401 – refreshing token"),
 * });
 *
 * const crm = new ZohoCRMClient({ clientId, clientSecret, authProvider: auth });
 * ```
 */
export class CustomAuthProvider implements IAuthProvider {
  private cache: CustomTokenResult | null = null;
  private fetchReason: "initial" | "expired" | "invalidated" = "initial";

  constructor(private readonly cfg: CustomAuthConfig) {}

  // ── Cache helpers ─────────────────────────────────────────────────────────

  private isCacheValid(): boolean {
    if (!this.cache) return false;
    if (this.cache.expiresAt === undefined) return false; // treat as single-use
    return Date.now() < this.cache.expiresAt - EXPIRY_BUFFER_MS;
  }

  // ── IAuthProvider ─────────────────────────────────────────────────────────

  invalidate(): void {
    this.cfg.onInvalidate?.();
    this.cache = null;
    this.fetchReason = "invalidated";
  }

  async getAccessToken(): Promise<string> {
    if (this.isCacheValid()) {
      return this.cache!.accessToken;
    }

    const reason = this.fetchReason;
    this.fetchReason = "expired"; // default for subsequent auto-refreshes

    const result = await this.cfg.fetchToken(reason);
    this.cache = result;
    return result.accessToken;
  }

  /** Returns the currently cached token result (useful for debugging). */
  getCachedToken(): Readonly<CustomTokenResult> | null {
    return this.cache;
  }
}
